sudo: false

language: node_js
node_js:
- "node"

matrix:
  include:
    - os: linux
      dist: focal
    - os: osx

services:
- xvfb

install:
- npm install
- npm run build

script:
- npm test --silent
- npm run public-ui-test
- npm run coverage:upload